### ISSUE TITLE
Updating and enhancing the documention

### ISSUE THREAD

**Issue by LSchueler** [GeoStat-Framework/GSTools#10]
We need some detailed description of the different covariance models and their parameters and we need some more examples of what can be done and how it can be done.

**Comment by MuellerSeb** [comment]
CovModel done. SRF and variogram left.

**Comment by LSchueler** [comment]
SRF done. variogram left.

**Comment by MuellerSeb** [comment]
Very nice! Thanks a bunch!

**Comment by LSchueler** [comment]
Variogram estimation has a really nice tutorial now,
check commit 135e286.
