### ISSUE TITLE
Cython language_level FutureWarning

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#11]
While building the c-extension with cython a FutureWarning comes up:

    FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/travis/build/GeoStat-Framework/GSTools/gstools/variogram/estimator.pyx

Since py2 is used implicitly, we should stick with that by setting:

    # cython: language_level=2

in the estimator.pyx

**Comment by LSchueler** [comment]
This warning only appears with relatively recent versions of Cython (in version 0.28.2 it doesn't exist).

With commit 9737184c215cc943e98a83bd95d245cc836a3177 the standard is set to Python version 2.
