### ISSUE TITLE
test.pypi not pushed

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#115]
Guess here is a typo:
https://github.com/GeoStat-Framework/GSTools/blob/370b7a2090e1a6c835a3971e6a2c88fce55ead8e/.github/workflows/main.yml#L106

Shouldn't it be `if: github.ref == 'refs/heads/develop' `?

**Comment by LSchueler** [comment]
Damn, thanks for pointing that out! I've fixed it directly on the develop branch with commit 3be10ebaa3.
