### ISSUE TITLE
Systematic artifacts with Exponential field generation

### ISSUE THREAD

**Issue by leonfoks** [GeoStat-Framework/GSTools#126]
I'm trying to generate a 2D field using the Exponential generator, however there seem to be artifacts when compared to a Gaussian.

A minimal example that works and will generate a smooth image.
```Python
import matplotlib.pyplot as plt
import gstools as gs
import numpy as np 
x = range(1024)
y = range(128)
model = gs.Gaussian(dim=2, var=1.0, len_scale=[1000,8], angles=-np.pi/100)
srf = gs.SRF(model, seed=201705320, upscaling='coarse_graining')
srf.structured([x, y])
srf.plot()
plt.axis()
```
![Figure_0](https://user-images.githubusercontent.com/19690642/104329678-744b3400-54ed-11eb-88a4-de1ca708e687.png)

If I simply switch to an Exponential, there appears to be a systematic artifact that is generated in the image.
```Python
import matplotlib.pyplot as plt
import gstools as gs
import numpy as np 
x = range(1024)
y = range(128)
model = gs.Exponential(dim=2, var=1.0, len_scale=[1000,8], angles=-np.pi/100)
srf = gs.SRF(model, seed=201705320, upscaling='coarse_graining')
srf.structured([x, y])
srf.plot()
plt.axis()
```
![Figure_1](https://user-images.githubusercontent.com/19690642/104329701-7f05c900-54ed-11eb-8796-3a513c5ae958.png)

I have played with a few things to rule out the call arguments, e.g. same discretization (field.shape), equal length len_scale, angle=None, and plotting with axis('equal').  There is always what appears to be a systematic (deterministic?) undulation.

Am I correct here? Or am I missing something?  My goal is to create a wider than tall cross section of something that resembles horizontal stratigraphy.  The discretization is different here by design.

Thanks!

**Comment by MuellerSeb** [comment]
Hey @leonfoks!

My educated guess is, that we see the modes of the underlying Randomization Method.
The fields are created by a superposition of sin and cos waves. To few of them can create artifacts like the one you encountered.
You can change that number of modes when initializing the SRF class:

```python
import gstools as gs
import numpy as np

x = range(1024)
y = range(128)
model = gs.Exponential(dim=2, var=1.0, len_scale=[1000,8], angles=-np.pi/100)
srf = gs.SRF(model, seed=201705320, upscaling='coarse_graining', mode_no=10000)
field = srf.structured([x, y])
ax = srf.plot()
ax.set_aspect("equal")
```
![Figure_2](https://user-images.githubusercontent.com/19690642/104330272-1ff48400-54ee-11eb-90d4-818442dd6b95.png)

At least IMHO it got better.

On the other hand, in case of Gaussian and Exponential variograms, the spectral sampling is performed (at least in 2D) by using the analytic ppf (percent point function or quantile function). All other models use MCMC. We could try to reimplement the Exponential model to force using the MCMC sampling. Then we can also use fewer modes (to much modes introduce noise here):
```python
import gstools as gs
import numpy as np

class Exp(gs.CovModel):
    def cor(self, h):
        return np.exp(-h)

x = range(1024)
y = range(128)
model = Exp(dim=2, var=1.0, len_scale=[1000, 8], angles=-np.pi / 100)
srf = gs.SRF(model, seed=201705320, upscaling='coarse_graining', mode_no=100)
field = srf.structured([x, y])
ax = srf.plot()
ax.set_aspect("equal")
```
![Figure_3](https://user-images.githubusercontent.com/19690642/104331545-7adaab00-54ef-11eb-9e79-2c50dba110b0.png)

Looks even better for me, at least at first appearance.

@LSchueler do you have another idea?

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
@LSchueler we could think about adding a switch to the RandMeth class to control the sampling strategy. Currently, it is only checked if the model has an analytical ppf defined: 
https://github.com/GeoStat-Framework/GSTools/blob/e28b00c95c50a94440bd874e7ce34ed3a71ea884/gstools/field/generator.py#L206

**Comment by LSchueler** [comment]
Hi!

It could be that you just see a visual artifact from the matplotlib-plotting methods. I'd have to look up the paper, but for a lot of applications mode numbers of 100 are sufficient.

Try this:

```python
import matplotlib.pyplot as plt
import gstools as gs
import numpy as np 
x = range(1024)
y = range(128)
model = gs.Exponential(dim=2, var=1.0, len_scale=[1000,8], angles=-np.pi/100)
srf = gs.SRF(model, seed=201705320, upscaling='coarse_graining')
srf.structured([x, y])
plt.contourf(srf.field.T, levels=10)
plt.show()
```
I think with the contour plot I can still see these patterns. Maybe with such an extreme anisotropy-ratio the mode number of 1000 is actually too small. The paper I mentioned above was only concerned with isotropic fields.

Interesting, maybe we should investigate the relationship between mode numbers and anisotropy ratios.

**Comment by LSchueler** [comment]
> @LSchueler we could think about adding a switch to the RandMeth class to control the sampling strategy. Currently, it is only checked if the model has an analytical ppf defined:
> 
> https://github.com/GeoStat-Framework/GSTools/blob/e28b00c95c50a94440bd874e7ce34ed3a71ea884/gstools/field/generator.py#L206

That is a nice idea.

**Comment by leonfoks** [comment]
Wooo Thanks for getting that fixed so quickly! Very much appreciated!
