### ISSUE TITLE
502 on https://gstools.readthedocs.io/ ?

### ISSUE THREAD

**Issue by jeffcsauer** [GeoStat-Framework/GSTools#138]
Hi all, 

Just wanted to flag that I am getting a 502 error about half the time when trying to navigate to https://gstools.readthedocs.io/ - is this happening to anyone else?

**Comment by MuellerSeb** [comment]
Hey there. Should be back on again. Downtime was due to the migration of readthedocs to AWS: https://blog.readthedocs.com/aws-migration/

Cheers, Sebastian
