### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by peter-pazak** [GeoStat-Framework/GSTools#164]
Hi,

I installed gstools via
pip install gstools
it installed from gstools-1.3.0-cp36-cp36m-win_amd64.whl
but when I do
import gstools
it ends with
from gstools.variogram.estimator import (
ImportError: DLL load failed: The specified module could not be found.
went back to gstools 1.2.1 and all workds fine

Thank you
Peter

**Comment by MuellerSeb** [comment]
Hey there,
sorry for the inconvenience! Will have a look at this!
Sebastian

**Comment by MuellerSeb** [comment]
I guess this is a problem with numpy and a binary incompatibility.
Could you try:
```
pip install -I gstools
```
and try again?

**Comment by MuellerSeb** [comment]
@LSchueler we should use the meta package for numpy as a build dep: https://github.com/scipy/oldest-supported-numpy

See:
https://scikit-hep.org/developer/packaging#special-additions-numpy

**Comment by MuellerSeb** [comment]
@peter-pazak what is your current numpy version? Upgrading numpy *could* solve the issue.

**Comment by peter-pazak** [comment]
Hi, sorry - I forgot to mention, this will probably be exactly the problem.
I am adding gstools to openquake, so my numpy is this one:
numpy @ https://wheelhouse.openquake.org/v2/windows/py36/numpy-1.18.2-cp36-cp36m-win_amd64.whl
Thank you very much for looking into this..
Peter

**Comment by peter-pazak** [comment]
Right, when I did
pip install -I gstools
it installed newer numpy and scipy, but pip complain these are incompatible

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openquake-engine 3.11.3 requires numpy<1.19,>=1.16, but you have numpy 1.19.5 which is incompatible.
openquake-engine 3.11.3 requires scipy<1.5,>=1.3, but you have scipy 1.5.4 which is incompatible.

**Comment by MuellerSeb** [comment]
If you don't require to run `openquake-engine` together with `gstools` you could think about a separate environment to solve this dependency war: https://virtualenv.pypa.io/en/latest/

But nevertheless we should provide compatibility with earlier versions of numpy which should be solved by #165

**Comment by peter-pazak** [comment]
Thank you very much, I even are fine with gstools 1.2.1, just whanted to know what caused the problem. Installing few days earlier worked fine, then suddenly on other machine yesterday didn't, then I realized there was version change, so wanted to let you know, just in case...
