### ISSUE TITLE
AttributeError: module 'gstools' has no attribute 'condSRF'

### ISSUE THREAD

**Issue by wtrainor** [GeoStat-Framework/GSTools#172]
Hello! I was following [your example](https://geostat-framework.readthedocs.io/projects/gstools/en/stable/examples/06_conditioned_fields/01_2D_condition_ensemble.html) to get a conditioned field and got the error that 'condSRF' doesn't exist.

This might be too much info (just trying to be helpful), but here's my conda list:
affine                    2.3.0                      py_0  
appdirs                   1.4.4                      py_0  
appnope                   0.1.2           py39hecd8cb5_1001  
argon2-cffi               20.1.0           py39h9ed2024_1  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     20.3.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
bleach                    3.3.0              pyhd3eb1b0_0  
blosc                     1.21.0               h046ec9c_0    conda-forge
boost-cpp                 1.74.0               h43a636a_2    conda-forge
brotli                    1.0.9                hb1e8313_2  
brotlipy                  0.7.0           py39h9ed2024_1003  
brunsli                   0.1                  h23ab428_0  
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.17.1               h9ed2024_0  
ca-certificates           2020.12.5            h033912b_0    conda-forge
cairo                     1.16.0               h8023c5d_1  
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
cffi                      1.14.5           py39h2125817_0  
cfitsio                   3.470                h01dc385_7    conda-forge
cftime                    1.4.1            py39he3068b8_0  
chardet                   4.0.0           py39hecd8cb5_1003  
charls                    2.2.0                h23ab428_0  
click                     7.1.2              pyhd3eb1b0_0  
click-plugins             1.1.1                      py_0  
cligj                     0.7.1            py39hecd8cb5_0  
cloudpickle               1.6.0                      py_0  
cryptography              3.4.7            py39h2fd3fbb_0  
curl                      7.75.0               h06286d4_0    conda-forge
cycler                    0.10.0           py39hecd8cb5_0  
cytoolz                   0.11.0           py39h9ed2024_0  
dask-core                 2021.4.0           pyhd3eb1b0_0  
dbus                      1.13.18              h18a8e69_0  
decorator                 5.0.6              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
double-conversion         3.1.5                haf313ee_1  
eigen                     3.3.7                h04f5b5a_0  
emcee                     3.0.2              pyh5ca1d4c_0    conda-forge
entrypoints               0.3              py39hecd8cb5_0  
expat                     2.2.10               hb1e8313_2  
ffmpeg                    4.3.1                hd856bfe_2    conda-forge
fiona                     1.8.18           py39h673eaac_1    conda-forge
fontconfig                2.13.1               ha9ee91d_0  
freetype                  2.10.4               ha233b18_0  
freexl                    1.0.6                h9ed2024_0  
fsspec                    0.9.0              pyhd3eb1b0_0  
gdal                      3.2.1            py39h0530131_7    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_0    conda-forge
geos                      3.9.1                h23ab428_0  
geotiff                   1.6.0                h4fce3c3_4    conda-forge
gettext                   0.21.0               h7535e17_0  
giflib                    5.2.1                haf1e3a3_0  
gl2ps                     1.4.2                h4cff582_0    conda-forge
glew                      2.1.0                h046ec9c_2    conda-forge
glib                      2.68.0               he49afe7_1    conda-forge
glib-tools                2.68.0               he49afe7_1    conda-forge
gmp                       6.2.1                h23ab428_2  
gnutls                    3.6.15               hed9c0bf_0  
gstools                   1.2.1            py39h7108016_1    conda-forge
h5py                      2.10.0           py39h90fc2a2_0  
hankel                    1.1.0                      py_0    conda-forge
hdf4                      4.2.13               h39711bb_2  
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
icu                       68.1                 h23ab428_0  
idna                      2.10               pyhd3eb1b0_0  
imagecodecs               2021.1.28        py39h5071892_0    conda-forge
imageio                   2.9.0              pyhd3eb1b0_0  
importlib-metadata        3.10.0           py39hecd8cb5_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
ipykernel                 5.3.4            py39h01d92e1_0  
ipython                   7.22.0           py39h01d92e1_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
jedi                      0.17.2           py39hecd8cb5_1  
jinja2                    2.11.3             pyhd3eb1b0_0  
joblib                    1.0.1              pyhd3eb1b0_0  
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.15                 hcb556a6_0    conda-forge
jsoncpp                   1.9.4                h940c156_2    conda-forge
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0            py39h6e9494a_6    conda-forge
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py39hecd8cb5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
jxrlib                    1.1                  haf1e3a3_2  
kealib                    1.4.14               h31dd65d_2    conda-forge
kiwisolver                1.3.1            py39h23ab428_0  
krb5                      1.17.1               hddcf347_0  
lame                      3.100                h1de35cc_0  
lcms2                     2.12                 hf1fd2bf_0  
lerc                      2.2.1                h23ab428_0  
libaec                    1.0.4                hb1e8313_1  
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libclang                  11.1.0          default_he082bbe_0    conda-forge
libcurl                   7.75.0               h8ef9fac_0    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libdap4                   3.20.6               h75eb3ff_1    conda-forge
libdeflate                1.7                  h9ed2024_5  
libedit                   3.1.20210216         h9ed2024_1  
libev                     4.33                 haf1e3a3_0  
libffi                    3.3                  hb1e8313_2  
libgdal                   3.2.1                h62a8350_7    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_20    conda-forge
libgfortran5              9.3.0               h6c81a4c_20    conda-forge
libglib                   2.68.0               hd556434_1    conda-forge
libiconv                  1.16                 h1de35cc_0  
libidn2                   2.3.0                h9ed2024_0  
libkml                    1.3.0             h3dc3bee_1012    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_0    conda-forge
libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libogg                    1.3.4                h35c211d_1    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               ha441bb4_0  
libpq                     13.1                 h052a64a_2    conda-forge
librttopo                 1.1.0                h5413771_6    conda-forge
libsodium                 1.0.18               h1de35cc_0  
libspatialindex           1.9.3                h23ab428_0  
libspatialite             5.0.1                h395434c_3    conda-forge
libssh2                   1.9.0                ha12b0ac_1  
libtasn1                  4.16.0               h9ed2024_0  
libtheora                 1.1.1                hb4e5f40_1  
libtiff                   4.2.0                h355d032_0    conda-forge
libunistring              0.9.10               h9ed2024_0  
libvorbis                 1.3.7                haf1e3a3_0  
libwebp-base              1.2.0                h9ed2024_0  
libxml2                   2.9.10               h802ca4f_3    conda-forge
libzopfli                 1.0.3                hb1e8313_0  
llvm-openmp               11.1.0               hda6cdc1_0    conda-forge
locket                    0.2.1            py39hecd8cb5_1  
loguru                    0.5.3            py39h6e9494a_2    conda-forge
lz4-c                     1.9.3                h23ab428_0  
markupsafe                1.1.1            py39h9ed2024_0  
matplotlib                3.3.4            py39h6e9494a_0    conda-forge
matplotlib-base           3.3.4            py39h8b3ea08_0  
meshio                    4.3.13             pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h9ed2024_1000  
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.3            py39ha81d895_7    conda-forge
mpich                     3.4.1              hd33e60e_104    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
munch                     2.5.0                      py_0  
mysql-common              8.0.23               h694c41f_1    conda-forge
mysql-libs                8.0.23               hbeb7981_1    conda-forge
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7            py39hecd8cb5_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
netcdf4                   1.5.6           nompi_py39h353b61e_102    conda-forge
nettle                    3.7.2                h230ac6f_1  
networkx                  2.5                        py_0  
notebook                  6.3.0            py39hecd8cb5_0  
nspr                      4.30                 hcd9eead_0    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numpy                     1.20.1           py39h3c955ea_0    conda-forge
olefile                   0.46                       py_0  
openh264                  2.1.1                hfd3ada9_0    conda-forge
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
packaging                 20.9               pyhd3eb1b0_0  
pandas                    1.2.3            py39h4d6be9b_0    conda-forge
pandoc                    2.12                 hecd8cb5_0  
pandocfilters             1.4.3            py39hecd8cb5_1  
parso                     0.7.0                      py_0  
partd                     1.2.0              pyhd3eb1b0_0  
pcre                      8.44                 hb1e8313_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.2.0            py39h5270095_0  
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               haf1e3a3_0  
pooch                     1.3.0              pyhd3eb1b0_0  
poppler                   0.89.0               hd735947_5    conda-forge
poppler-data              0.4.10               hecd8cb5_0  
postgresql                13.1                 ha63e576_2    conda-forge
proj                      7.2.0                h78d1473_2    conda-forge
prometheus_client         0.10.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
prompt_toolkit            3.0.17               hd3eb1b0_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pugixml                   1.11.4               he49afe7_0    conda-forge
pycparser                 2.20                       py_2  
pyevtk                    1.2.0              pyh050c7b8_0    conda-forge
pygments                  2.8.1              pyhd3eb1b0_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyproj                    3.0.1            py39he1749b9_0    conda-forge
pyqt                      5.12.3           py39h6e9494a_7    conda-forge
pyqt-impl                 5.12.3           py39hef7122c_7    conda-forge
pyqt5-sip                 4.19.18          py39hd8f94c5_7    conda-forge
pyqtchart                 5.12             py39hef7122c_7    conda-forge
pyqtwebengine             5.12.1           py39hef7122c_7    conda-forge
pyrsistent                0.17.3           py39h9ed2024_0  
pysocks                   1.7.1            py39hecd8cb5_0  
python                    3.9.2           h2502468_0_cpython    conda-forge
python-dateutil           2.8.1              pyhd3eb1b0_0  
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
pyvista                   0.29.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py39he3068b8_4  
pyyaml                    5.4.1            py39h9ed2024_1  
pyzmq                     20.0.0           py39h23ab428_1  
qt                        5.12.9               h126340a_4    conda-forge
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
rasterio                  1.2.1            py39hafb7765_2    conda-forge
readline                  8.1                  h9ed2024_0  
requests                  2.25.1             pyhd3eb1b0_0  
rtree                     0.9.7            py39hecd8cb5_1  
schwimmbad                0.3.2            py39h6e9494a_0    conda-forge
scikit-image              0.18.1           py39h089d6f7_0    conda-forge
scikit-learn              0.24.1           py39h1f17f7f_0    conda-forge
scipy                     1.6.1            py39h056f1c0_0    conda-forge
scooby                    0.5.7              pyhd8ed1ab_0    conda-forge
send2trash                1.5.0              pyhd3eb1b0_1  
setuptools                52.0.0           py39hecd8cb5_0  
shapely                   1.7.1            py39h1d9c377_4    conda-forge
six                       1.15.0           py39hecd8cb5_0  
snappy                    1.1.8                hb1e8313_0  
snuggs                    1.4.7                      py_0  
sqlite                    3.35.4               hce871da_0  
tbb                       2020.3               h879752b_0  
tbb-devel                 2020.3               h879752b_0  
terminado                 0.9.4            py39hecd8cb5_0  
testpath                  0.4.4              pyhd3eb1b0_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tifffile                  2021.3.31          pyhd3eb1b0_1  
tiledb                    2.2.6                he9a4fb4_0    conda-forge
tk                        8.6.10               hb0a8c7a_0  
toolz                     0.11.1             pyhd3eb1b0_0  
tornado                   6.1              py39h9ed2024_0  
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5              pyhd3eb1b0_0  
transforms3d              0.3.1                      py_0    conda-forge
tzcode                    2021a                h0d85af4_1    conda-forge
tzdata                    2020f                h52ac0ba_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
utfcpp                    3.1.2                h694c41f_1    conda-forge
vtk                       9.0.1           no_osmesa_py39h3ee05c5_105    conda-forge
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1            py39hecd8cb5_1  
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1            py39hecd8cb5_0  
x264                      1!152.20180806       h1de35cc_0  
xarray                    0.17.0             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                hd3a8c1e_2    conda-forge
xz                        5.2.5                h1de35cc_0  
yaml                      0.2.5                haf1e3a3_0  
zeromq                    4.3.4                h23ab428_0  
zfp                       0.5.5                h23ab428_6  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.9                h322a384_0  

Thanks for any advice!

**Comment by LSchueler** [comment]
Hi! We recently released version 1.3 of GSTools, which broke backwards-compatibility with the conditioned fields. The example you are refering to shows the new way of handling conditioned fields.
I think your best option would be to update GSTools to the newest version. However, if you would like to stick to version 1.2.1, I can paste the old example here.

**Comment by wtrainor** [comment]
Happy to update to the newest version...but now getting 
`__call__() got an unexpected keyword argument 'seed'`
and `??krige.structured` doesn't supply much guidance.

**Comment by LSchueler** [comment]
Hmm, I just had a look at the [example](https://github.com/GeoStat-Framework/GSTools/blob/develop/examples/06_conditioned_fields/01_2D_condition_ensemble.py) again and the `seed` attribute is handed over to the `gs.CondSRF.structured` method. The kriging class doesn't need any seed, as it is completely deterministic.

The `CondSRF` class takes an instance of a kriging class to generate conditioned spatial random fields. That is where you need a seed to reproduce the exact fields. This happens on line 30 in the linked example.

**Comment by wtrainor** [comment]
Sorry, I wasn't clear, I got the error here
`cond_srf.structured([x, y], seed=i)`
not sure what line that is, I'm looking [here](https://geostat-framework.readthedocs.io/projects/gstools/en/stable/examples/06_conditioned_fields/01_2D_condition_ensemble.html). Is there somewhere else I should look with line numbers?

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-67-4f50e8d8b8b7> in <module>
      2 field = []
      3 for i in range(ens_no):
----> 4     field.append(krige.structured([x, y],seed=i)) # removed , seed=i

~/tools/miniconda3/envs/GS_env/lib/python3.9/site-packages/gstools/field/base.py in structured(self, *args, **kwargs)
     93         """
     94         call = partial(self.__call__, mesh_type="structured")
---> 95         return call(*args, **kwargs)
     96 
     97     def unstructured(self, *args, **kwargs):

TypeError: __call__() got an unexpected keyword argument 'seed'`

**Comment by LSchueler** [comment]
I'm just guessing here, but maybe you forgot the last line of the first codeblock `cond_srf = gs.CondSRF(krige)`?

The line you pasted which throws the exception is ` field.append(krige.structured([x, y],seed=i))`. But if you stick to the example it should be `field.append(cond_srf.structured([x, y], seed=i))`.

You could use the [example](https://github.com/GeoStat-Framework/GSTools/blob/develop/examples/06_conditioned_fields/01_2D_condition_ensemble.py) I linked to in my previous post to get a complete and working example script and make your changes there?

**Comment by MuellerSeb** [comment]
I am also guessing your are calling the `krige` instance itself instead of `cond_srf`.
And note, that you can pass a `seed` to the `gs.CondSRF`:
```python
cond_srf = gs.CondSRF(krige, seed=1234)
```
Since the keyword-arguments are forwarded to the generator (RandMeth in this case) like with the `SRF` class.

**Comment by wtrainor** [comment]
YES, that's it. So sorry...thank you!
