### ISSUE TITLE
Rework field transformations workflow

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#195]
### Discussed in https://github.com/GeoStat-Framework/GSTools/discussions/168

At the moment, transformations work on a given field and modify the `field` attribute inplace.

Ideas:
- return the transformed field
- add a selector to specify the field attribute name (`"field"` by default)
- add `store` keyword (`True` by default to modify inplace, `False` to only return, `<str>` to store in other attribute given by name)

### Example
```python
import gstools as gs
x = y = range(100)
model = gs.Gaussian(dim=2, var=1, len_scale=10)
srf = gs.SRF(model)
srf.structured([x, y])
log_field = gs.transform.normal_to_lognormal(srf, field="field", store="log_field")
srf.plot(field="log_field")
print(srf.field)
print(srf.log_field)
```
This has the advantage, that the original field is still available and the new field is also stored in the class.
The plotting routines are already able to select a field by name.

We should use the `Field.post_field` method to store the fields by name.

**Comment by LSchueler** [comment]
I would really like to have the keywords `input_field` and `output_field` or something like that, but that doesn't really work for the ideas you suggested, unless we add another argument `save` or something to be consistent with suggestion #196.

But these are all good ideas and they are features which are obviously missing.

**Comment by MuellerSeb** [comment]
To be in line with #196 I would then vote for `field` and `store` as described above.
