### ISSUE TITLE
Control of field storage in Field class and subscript option

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#196]
### Followup to #195 and revival of #65

We already provide the `post_field` method with functionality currently not fully used:
https://github.com/GeoStat-Framework/GSTools/blob/21c97fc7426864add2430addcaf465da8993d227/gstools/field/base.py#L217

We should provide arguments in `Field.__call__` (and in child classes) that are forwarded to this method:
- `name`: name of the attribute (`None` by default for current behavior, for multiple names use the same workflow as in `Field.mesh`)
- `save`: control if the field(s) should be stored anyway (`True` by default)

When doing so, we could modify the `post_field` method to create a list of stored fields (`Field.field_names`).
Maybe we could now also implement the accessing framework with `__getitem__`:
```python
def __getitem__(self, field):
    if field in self.field_names:
        return getattr(self, field)
    raise ValueError(f"Field: requested field '{field}' not present")
```

And finally this could go hand in hand with using the `pos` tuple that is stored in the field. So passing `pos=None` should reuse `self.pos` and throw an Error when this is not set yet (done in `pre_pos` method).

Also the present `meshtype` should be used then and an Error should be thrown when using the specific method `.structured` or `unstructured` conflicting with the present `mesh_type`.

@LSchueler do you have strong opinions on that?

**Comment by MuellerSeb** [comment]
For clarification:
### What is the improvement in comparison to #65 
- no mesh handling (since we support `meshio`, I don't see the need to come up with an own solution written from scratch)
- only accessing fields with `__getitem__` and setting internally with `post_field`
- minimal changes and preserving current behavior as default

**Comment by LSchueler** [comment]
Yummy, syntactic sugar! I like the `__getitem__`.

I've become a bit hesitant to add more and more optional arguments to all kinds of methods, but I think we are still harmless compared to beasts like pandas.

I think we discussed the name of the argument `save` already, pandas uses `inplace`, but I also don't like that one a lot.

Just some random thoughts and apart from them, I dig your suggestions :+1:

**Comment by MuellerSeb** [comment]
Since `inplace` is not entirely correct, I would vote for `store` to kill two birds with one stone: Allow naming the field and control storage. Then we also just add one keyword instead of `name` and `save`. store would be `True` by default to reproduce current behavior or a name or list of names if multiple fields are produced (krige field and variance).
Naming could then be further controlled in the way the `mesh` method does.

Also this fits the suggestions of #195
