### ISSUE TITLE
Tutorials missing

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#20]
There are still tutorials missing for the following new features:

- [x] simple and ordinary kriging
- [x] conditioned field generation
- [x] field transformations
- [x] plotting routines for fields
- [x] random flow field generation
- [x] parallel compilation of GSTools

**Comment by LSchueler** [comment]
- [x] plotting routines for fields with commit f708e2
- [x]  random flow field generation with commit b78c20

**Comment by MuellerSeb** [comment]
All other tutorials added with https://github.com/GeoStat-Framework/GSTools/commit/0822a89897f278b6d28f5a8aeba86fc3c06804f1

Parallel compilation of GSTools is described in the Quickstart.
