### ISSUE TITLE
Field class: Joint base class for SRF and kriging classes.

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#21]
A lot of functionality of the SRF, Simple and Ordinary classes are overlapping. To  get a better maintainability of these classes it would be good to have a base class providing the common properties and methods.

**Comment by LSchueler** [comment]
Definitely a good idea. Something to do, when you have a little bit of spare time I guess ;-)

**Comment by MuellerSeb** [comment]
Done with:
https://github.com/GeoStat-Framework/GSTools/commit/2ed04c65b8cb6e7e7481059e69d05fd828372279
