### ISSUE TITLE
Issue trying to install with conda (_openmp_mutex error)

### ISSUE THREAD

**Issue by darribas** [GeoStat-Framework/GSTools#210]
I'm trying to cut the new [`gds_env`](https://github.com/darribas/gds_env) container and would love to include `GSTools`. When I run the install, I get the following error:

```docker
package gstools-1.1.1-py37h516909a_0 requires python >=3.7,<3.8.0a0, but none of the providers can be installed
```

Is there any reason why it would not work with Python 3.9?

**Comment by MuellerSeb** [comment]
Hey there! That is a very interesting environment you are working on.

GSTools needs the llvm version of openmp (see [here](https://github.com/conda-forge/gstools-feedstock/blob/77ad4f6e8147e224d38f3f8f71dbda4dd34bb113/recipe/meta.yaml#L35)). Maybe this could be change by use to be the GNU variant on Linux, but it is not fork-safe. As written [here](https://conda-forge.org/docs/maintainer/knowledge_base.html#openmp), you could try forcing llvm with this:
```bash
conda install _openmp_mutex=*=*_llvm
```
Like you did with `openblas` in [your docker file](https://github.com/darribas/gds_env/blob/6dc5ff09e06977b41560bc94021ff98e7417159b/gds_py/Dockerfile#L16).

Maybe this helps. Thanks for choosing GSTools for the `gds_env`! :blush:

Cheers, Sebastian

**Comment by MuellerSeb** [comment]
> ```
> - package gstools-1.3.3-py36hc4f0c31_0 requires _openmp_mutex * *_llvm, but none of the providers can be installed
> ```
That is still the build-number `0`. Since I needed to update the feedstock and conda-forge dropped py36 support, you shouldn't use Python 3.6 (EOL in Dec.'21). Could you use at least Python 3.7 and build-number `1`?

**Comment by darribas** [comment]
I have no idea why it's picking up `gstools-1.3.3-py36hc4f0c31_0`. Any way in `conda`/`mamba` I could explicitly ask for `py39` and build `1`?

**Comment by darribas** [comment]
According to [this answer](https://stackoverflow.com/a/48129025/1743507) I should be able to use `gstools=1.3.3=py39he80948d_1` in the install command to pin explicitly to a build. When I do that, I get the following error:

```
- nothing provides requested gstools ==1.3.3 py39he80948d_1
```
