### ISSUE TITLE
Refactor Cython routines to have same signatures as rust implementations

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#216]
In order to have drop-in replacements for the Cython routines we need to refactor the existing cython routines:
- variogram
  - remove `dim` argument from `directional`, `unstructured`
    https://github.com/GeoStat-Framework/GSTools-Core/blob/afe9ec1134d19fc9bde8ae8466132433315718a0/src/variogram.rs#L240
    https://github.com/GeoStat-Framework/GSTools-Core/blob/afe9ec1134d19fc9bde8ae8466132433315718a0/src/variogram.rs#L357

**Comment by LSchueler** [comment]
Closed with PR #215
