### ISSUE TITLE
Identify scalar and vector fields

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#23]
At the moment the ``SRF`` class can produce scalar or vector valued spatial fields.
To simplify plotting and export routines it would be good to have an identifier for that.

**Comment by MuellerSeb** [comment]
Suggestion:

Maybe the ``Field`` class could have an attribute ``value_type`` which is either ``scalar`` or ``vector`` or whatever comes in the future (For example the VTK data-format distinguishes between SCALAR, VECTOR and TENSOR).

For the plotting and exporting routine we could then use ``value_type`` as a parameter, which is ``None`` by default and takes the field attribute value then or it could be specified by the user, since the plotted or exported field could also be specified by the user and there, the value type could differ from the "main" type.

The question now is, how to set the ``value_type`` internally, since it may need to be set by the generator of the SRF class (``RandMath`` and ``IncomprRandMeth`` are the crux of the matter here)

Since the generator is set by a class method here:

https://github.com/GeoStat-Framework/GSTools/blob/fb009118f1824e57c2d430b7190943d386aa965e/gstools/field/srf.py#L250

we could associate a ``value_type`` with the generators and copy it to the SRF class at that point.

**Comment by LSchueler** [comment]
We already have the dictionary

`GENERATOR = {
    "RandMeth": RandMeth,
    ...
}`

in `srf.py`, which could be turned to something like

`GENERATOR = {
    "RandMeth": [RandMeth, "SCALAR"],
    ...
}`

**Comment by MuellerSeb** [comment]
Why not make ``value_type`` also an attribute of the Generators and do something like:

    self.value_type = self.generator.value_type

In the ``set_generator`` routine? I think we could prevent redundancy with that.

**Comment by LSchueler** [comment]
OK, I made a suggestion in the `field_value_type` branch:

940c07b

**Comment by MuellerSeb** [comment]
I've added some comments! ..and I like it :-)

**Comment by LSchueler** [comment]
OK, with commit  1614a43 I merged this stuff.
