### ISSUE TITLE
Installation on the Apple Silicon (M1 Pro & M1 Max)

### ISSUE THREAD

**Issue by MatusGasparik** [GeoStat-Framework/GSTools#232]
I am trying to `conda install gstools -c conda-forge` on a macbook with the new Apple silicon, however I get the `PackagesNotFoundError`. 

Are there no wheels for `osx-arm64` yet? What is the recommended installation method?

Here, the output from running `conda info`:

```
     active environment : base
    active env location : /Users/matus/miniconda3
            shell level : 1
       user config file : /Users/matus/.condarc
 populated config files : /Users/matus/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.11.final.0
       virtual packages : __osx=12.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/matus/miniconda3  (writable)
      conda av data dir : /Users/matus/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/matus/miniconda3/pkgs
                          /Users/matus/.conda/pkgs
       envs directories : /Users/matus/miniconda3/envs
                          /Users/matus/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.25.1 CPython/3.8.11 Darwin/21.2.0 OSX/12.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by MuellerSeb** [comment]
Hey there,
thanks for the reminder. The ARM64 migrator failed: https://github.com/conda-forge/gstools-feedstock/pull/25

Since this is automated by conda-forge, I need to wait for them to help me. I hope this will be solved soon.

In the meantime, you could use the pip version of gstools, even inside your conda environment. There we provide wheels for apple silicon:
```bash
pip install gstools
```

**Comment by MatusGasparik** [comment]
Thanks, Sebastian for your prompt reply! I'll go with the `pip install` in the meantime.

**Comment by MuellerSeb** [comment]
The ARM migrator is now merged. So conda builds for Apple Silicon will arrive within the next hours. Unfortunately, they don't provide OpenMP parallelization but this will be solved in the future with the Rust backend [GSTools-Core](https://github.com/GeoStat-Framework/GSTools-Core/).

**Comment by MuellerSeb** [comment]
@MatusGasparik if you try the conda ARM64 builds, could you maybe report if everything is working? :relaxed:

**Comment by MatusGasparik** [comment]
@MuellerSeb OK. I'll report back once I successfully install with conda...

**Comment by MatusGasparik** [comment]
The conda install  for  `osx-arm64` seems to work now.  Closing this issue.
