### ISSUE TITLE
At risk of circular imports

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#24]
Since all imports within the package are absolute we are at risk to run into circular imports when something is changed.

See for example this bug-fix: https://github.com/GeoStat-Framework/GSTools/commit/73ba330642261f9a59a955dbd82a1037d78edb89

Possibilities:
https://stackoverflow.com/questions/7336802/how-to-avoid-circular-imports-in-python

**Comment by LSchueler** [comment]
Did I get you correctly, that you are afraid to run into a problem sometime in future and the problem only affects Python 2, which will be deprecated in the near future?

Source from one of the answers of the link you provided:

"The ImportError and AttributeError issues only occur in python 2. In python 3 the import machinery has been rewritten and all of these import statements (with the exception of 4) will work, even with circular dependencies."

I suggest sitting back, having a cup of coffee and waiting for Python 2 to finally vanish ;-)

**Comment by MuellerSeb** [comment]
I ran into that problem and I am using Python3 .. I was actually a bit confused by this statement in the stackoverflow conversation.
Just try loading gstools from commit https://github.com/GeoStat-Framework/GSTools/commit/f2f6c084fcec018aee663bf16f7dc8f2e1c86c8e

**Comment by MuellerSeb** [comment]
Since we now check the source code with pylint we should be safe here!
