### ISSUE TITLE
Change Licence to MIT or LGPL?

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#25]
The GNU license is good, but has some conditions for users that are a bit to restrictive in my opinion. For example, the GNU GPL3 license demands the same license for derived software.

I think, GSTools should be usable by the biggest possible user group and therefore I would suggest the MIT license, which is "a short and simple permissive" one.

**Comment by MuellerSeb** [comment]
Any opinions on this?
@fhesze , @LSchueler , @AlrauneZ

**Comment by fhesze** [comment]
Klingt gut. Keine Einwände meinerseits.

Am 28.08.19 um 14:07 schrieb Sebastian Müller:

**Comment by LSchueler** [comment]
As GSTools being scientific software I believe that it should also incorporate the idea of free and open-source software, namely to promote the free exchange of ideas and technology. Therefore I don't like the idea that the MIT license allows people to modify the code without giving it back to the public.

A compromise is always the lesser GPL, which enforces people to publish modified versions of the code under the same license, but which still allows people to use the software in proprietary code. I don't think that you in any way shrink the size of the possible user group by using the LGPL.

**Comment by MuellerSeb** [comment]
OK. I think we go with the LGPL3.0 then. If I understand it right, all you have to do, if you use this package in your code is  to keep the LGPL license for the gstools part, right? It doesn't mean to use the LGPL in the rest of the 3rd party code?

**Comment by MuellerSeb** [comment]
Closing with: https://github.com/GeoStat-Framework/GSTools/commit/1c8a0ef4fdfcb6fd665bca0b92f6b8bdf4cf5365
