### ISSUE TITLE
Requirements for Scipy Innacurate

### ISSUE THREAD

**Issue by Derekbenj** [GeoStat-Framework/GSTools#256]
The requirements suggest that any scipy version greater than or equal to 1.1.0 will support this framework, but as of 1.7.0, 'pinv2' is depreciated from scipy.linalg, after which version the old pinv and pinv2 are consolidated to pinv only. Attempting to import gstools with any scipy version greater than 1.7 fails. As a bandaid fix, line 38 of gstoools/kringe/base.py can be changed from:

P_INV = {"pinv": spl.pinv, "pinv2": spl.pinv2, "pinvh": spl.pinvh}

to 

P_INV = {"pinv": spl.pinv, "pinv2": spl.pinv, "pinvh": spl.pinvh}

**Comment by MuellerSeb** [comment]
Hi there,
this was already reported here: https://github.com/GeoStat-Framework/GSTools/issues/246
and is already solved here: https://github.com/GeoStat-Framework/GSTools/pull/247
It will be part of the next release v1.4 that will come in the next days.

Thanks for your report.
