### ISSUE TITLE
generating correlated log-normally distributed fields

### ISSUE THREAD

**Issue by hodaj** [GeoStat-Framework/GSTools#26]
Is it possible to generate a correlated log-normally random field using GeoStatTools? If so would you please give me some hints?

**Comment by MuellerSeb** [comment]
Hey hodaj,
of course it is possible (and it is one of the main applications).
Let's use the introduction example:

    import numpy as np
    from gstools import SRF, Gaussian
    # structured field with a size of 100x100 and a grid-size of 1x1
    x = y = range(100)
    model = Gaussian(dim=2, var=1, len_scale=10)
    srf = SRF(model)
    field = srf((x, y), mesh_type='structured')
    log_normal = np.exp(log_normal)

Then the field stored in ``log_normal`` is log-normal distributed and the log values are correlated according to a gaussian covariance model.

Does that help?

With the next release 1.1 there will come a range of built in transformations, that will make these transformations easier.

Cheers,
Sebastian

**Comment by hodaj** [comment]
Hi Sebastian,

Thanks a lot for the quick reply. 
In this manner I will be creating a correlated normal field and then transforming it to a log-normal field. The problem is that the correlation length of the log-normal field will be different from the correlation length I specified for the normal field. 
I wish to generate hundreds of log-normally distributed fields with the same statistics (mean, variance and correlation length). I can adjust the mean and variance of the log-normal field but I am not sure about the correlation length. That's why I wanted to know if it is possible to specify the correlation length of the log-normal field from the beginning so that I always get a consistent result.

Cheers,
Hoda

**Comment by MuellerSeb** [comment]
Hey Hoda,

you are right, that the correlation length of the log-normal field is not the given one. But in hydrogeology and geostatistics these values mostly refer to the properties of the log-values.
This means, the given approach above is the classical on.

GSTools was designed to generate ensembles of fields following the same statstics. You can set a seed for each ensemble member. Look at the following example to create 128 lognormal fields:

    import numpy as np
    from gstools import SRF, Gaussian
    # structured field with a size of 100x100 and a grid-size of 1x1
    x = y = range(100)
    model = Gaussian(dim=2, var=1, len_scale=10)
    srf = SRF(model)
    ens_no = 128
    lognormal_fields = []
    for i in range(ens_no):
        field = srf.structured((x, y), seed=i)
        lognormal_fields.append(np.exp(field))

``lognormal_fields`` is now a list containing 128 fields each created with the same statistics.

Does this help?
Cheers, Sebastian

**Comment by MuellerSeb** [comment]
Also have a look at the Tutorials:
https://gstools.readthedocs.io/en/latest/tutorial_01_srf.html

**Comment by hodaj** [comment]
Thanks a lot Sebastian,. It does help to know that this is the standard approach.
Yes I went through the tutorials. Great job in preparing the detailed document with lots of examples. 

Best regards,
Hoda

**Comment by MuellerSeb** [comment]
If it helps, we are on the right track! ;-)
All the best with your project!
Cheers, Sebastian
