### ISSUE TITLE
Export vector fields

### ISSUE THREAD

**Issue by LSchueler** [GeoStat-Framework/GSTools#27]
Trying to export a vector valued field results in an exception. This should be supported and I guess we should stay in-line with the OGS conventions.

**Comment by MuellerSeb** [comment]
By "OGS conventions" you mean splitting the vector-field in X, Y and Z component by adding the suffixes "_X", "_Y" and "_Z"?
This approach should be easy to implement.

**Comment by LSchueler** [comment]
Exactly, Paraview can also handle that convention.

**Comment by MuellerSeb** [comment]
Done with: https://github.com/GeoStat-Framework/GSTools/commit/1a293a43d19fd0837de4e72907890f00baf9d40b
