### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by javoha** [GeoStat-Framework/GSTools#28]
Hello,

when trying to install `gstools` either by using the normal `pip install gstools` or the development version `pip install https://github.com/GeoStat-Framework/GSTools/archive/master.zip` I get the following error:

**ERROR: Could not find a version that satisfies the requirement gstools (from versions: none)
ERROR: No matching distribution found for gstools**

I tried different environments and feel like the problem is not on my side but I might be very wrong. Do you have any ideas what the issue might be?

Thanks alot and best wishes.

**Comment by MuellerSeb** [comment]
Hey Javoha,
that sounds strange to me.. what version of python are you using?
There will be a new release of GSTools next week. Maybe it's working for you afterwards.

**Comment by javoha** [comment]
Hi, thanks for taking a look. I am using python 3.7 - I also tried different environments but the problem remains. Maybe the new releases solves this.

**Comment by MuellerSeb** [comment]
Hey there.

What happens, if you install the recently released RC:

    pip install --pre -U gstools

Maybe this helps. Otherwise, if there are network permission problems, download the package [v1.1.0.rc1](https://github.com/GeoStat-Framework/GSTools/archive/v1.1.0.rc1.zip), unzip it and run the following command in the folder containing the ``setup.py``:

       pip install -U .

**Comment by javoha** [comment]
Hi,

it was definitely a network problem at our university and everything runs perfectly now, after the recent release and resolving our problems here. Thanks a lot for looking into it and sorry for the inconveniences.

**Comment by MuellerSeb** [comment]
Cool. Closed then.
