### ISSUE TITLE
Feature Enhancement: Unit selection and max_distance with Variogram where latlon = True

### ISSUE THREAD

**Issue by Megil-Zesty** [GeoStat-Framework/GSTools#282]
When defining a variogram with latlon=True, I would love to be able to set max_distance directly in  gs.vario_estimate() as well as the units for the distance. Then, when plotting the variogram data, I could see semivariance vs distance.

**Comment by MuellerSeb** [comment]
Could you provide a code-example? I don't think I fully understand your problem.

**Comment by MuellerSeb** [comment]
#308 solves at least the units issue for the CovModel representation, that can now be defined with the new `geo_scale` attribute of the CovModel. You can choose between `KM_SCALE` (earth radius in km as reference), `DEGREE_SCALE` (length scale in degrees) and `RADIAN_SCALE` (default, length scale in radians). To use other distance units, you could multiply conversion factors to `KM_SCALE`, like `1000 * KM_SCALE` to have a meter scale.

The `vario_estimate` routine will always use radians for the great circle distance. To have a better plotting, you could multiply the bin centers with one of the scales given above to have another unit for the x-axis.

For the other problem I assume you mean the remaining arguments of the [standard_bins](https://geostat-framework.readthedocs.io/projects/gstools/en/v1.4.1/generated/generated/gstools.variogram.standard_bins.html) routine, namely `bin_no` and `max_dist`.
This seems like a useful extension. I will take a look.

**Comment by MuellerSeb** [comment]
`geo_scale` was added to `vario_estimate` to select the units of the bins with #308

**Comment by MuellerSeb** [comment]
Also additional keywords will be forwarded to `standard_bins`, so this will be solved.
