### ISSUE TITLE
Stop supporting Python<3.6

### ISSUE THREAD

**Issue by banesullivan** [GeoStat-Framework/GSTools#30]
I propose this library stop supporting all Python distributions below 3.6. Why? 2.7 is planned to be no longer supported fairly soon and it can be a major maintenance issue to support 2.7 code alongside 3.x code. See https://python3statement.org/ as most open source projects have already stopped supporting Python 2.7

I also recommend committing to support 3.6+ only since conda-forge no longer builds 3.5 packages.

Also, this would make #29 a bit easier as PyVista on Python<3.6 is only **unofficially** supported on some platforms

**Comment by MuellerSeb** [comment]
Hey @banesullivan ,

we are planning to drop support for py2 starting from 1.1.2020 and with GStools v1.2.

At the moment we don't provide conda builds, so this could also be done with v1.2.

Dropping py35 support seems a bit harsh at the moment, since it is still in use, not at its EOL (Sep 2020?) and in some LTS OS it is also still the default version.

I will think about that! Thanks for your hints!
Sebastian

**Comment by banesullivan** [comment]
Thanks for the feedback! I'll proceed with #29 to make sure the API is backward compatible and working all the way back to Python 2.7 to be in line with your goals.

I think in PyVista we still technically support Python 3.5 but there were some major changes with dictionaries that in my opinion make dropping 3.5 and below worthwhile... *(in fact, PyVista probably assumes a lot about dictionaries that makes use with 3.5 a bad idea, but that's a separate issue)*

**Comment by LSchueler** [comment]
Now I'm curious! I thought, only the internals of the dict implementation have changed in order to make them more memory efficient. And that developers shouldn't even rely on the order-preservation. Could you go a little bit more into detail on what you are relying?

**Comment by banesullivan** [comment]
> I thought, only the internals of the dict implementation have changed in order to make them more memory efficient.

Ah, after looking it up again, it should simply be the internals that changed so it shouldn't affect users/developers... 

> And that developers shouldn't even rely on the order-preservation. Could you go a little bit more into detail on what you are relying?

A while back I implemented some fancy dictionary-VTK interfaces in a PyVista offshoot project and remembered having issues on 3.5 and below which is why I assumed there were major changes... I can't really remember what those issues were now though 🙃

**Comment by LSchueler** [comment]
Ah okay :-)

By the way, I'd also be more than glad to drop the support for some of the older Python versions and use some of the newer features, but our target group <strike>is lazy</strike> focuses on their work and does not update their OS and Python versions regularly.
