### ISSUE TITLE
Gaussian variogram different from Webster, 2007

### ISSUE THREAD

**Issue by rlsandovalp** [GeoStat-Framework/GSTools#305]
Hi,

Just wondering why the Gaussian variogram differs from the equation written by Webster (2007).

There, the equation reads 
$\gamma (h) = c\left{1-exp\left(-\frac{h^2}{r^2}\rigth)\rigth}$

**Comment by LSchueler** [comment]
[Here](https://geostat-framework.readthedocs.io/projects/gstools/en/latest/examples/02_cov_model/04_different_scales.html#sphx-glr-examples-02-cov-model-04-different-scales-py) you can see a few different scales, which are commonly used.
