### ISSUE TITLE
The Herten aquifer example is not compatible with pandas version >= 0.25.0

### ISSUE THREAD

**Issue by LSchueler** [GeoStat-Framework/GSTools#33]
Executing the script `gstools/examples/08_variogram_estimation.py` with pandas version >= 0.25.0 results in a pretty obscure error

`File "pandas/_libs/parsers.pyx", line 534, in pandas._libs.parsers.TextReader.__cinit__
OverflowError: can't convert negative value to npy_uint64`

The problem is in line 155 of the helper script `gstools/examples/tools/vtk2gslib.py`, which gets downloaded by the example script. `header=-1` has to be changed to `header=None`.

@MuellerSeb could you contact Peter Beyer and ask him if it is possible to upload a corrected version?
If that is not possible, maybe we have to do some meta programming and edit the source code.

**Comment by MuellerSeb** [comment]
Or maybe we use pyvista to read the vtk file?

**Comment by LSchueler** [comment]
I have actually never looked into the accompanying script... at least as long as it worked ;-)

I made a funny little fix with commit f9146584807, but yeah, pyvista is maybe a more sustainable solution.

**Comment by MuellerSeb** [comment]
With pyvista we could also have a plot of the original input data in 3D. That's the future. I tell you!

**Comment by MuellerSeb** [comment]
This example now uses pyvista.
