### ISSUE TITLE
Parallel sampling with emcee

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#35]
Since emcee provides parallel sampling with schwimmbad, we should think about including this.

Have a look here:
https://schwimmbad.readthedocs.io/en/latest/examples/index.html#using-multipool-with-emcee

**Comment by KVROHITH098** [comment]
Hi I am from Node.js how may I help you today!

**Comment by MuellerSeb** [comment]
Not need anymore since we could vectorize the sampling (our models are light-weight): #344
