### ISSUE TITLE
Dropping Python 2.7 and 3.4 support

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#40]
Since Python 2 will reach it's EOL on [**1. Jan 2020**](https://www.python.org/doc/sunset-python-2/), we will drop support for it, too.

The next minor release (v1.2) will then be **Python 3 only**.

Since TravisCI supports Windows but only for Python 3 we can then drop the use of Appveyor and stick to one CI system.

**Comment by MuellerSeb** [comment]
See here: https://github.com/python3statement/python3statement.github.io/pull/272

**Comment by LSchueler** [comment]
Python 3.4 has already reached its EOL on 2019-03-18.

We should drop the support of that version too.

**Comment by MuellerSeb** [comment]
Now we have to fulfill our promise:
https://python3statement.org/
:blush:

**Comment by MuellerSeb** [comment]
We should add this line in ``setup.py``:
```python
python_requires='>=3.5',
```
See here:
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by LSchueler** [comment]
Note for self:
remove "Python 2" classifier from setup.py too whenn dropping support.

**Comment by MuellerSeb** [comment]
Done with #43
