### ISSUE TITLE
Routines missing in documentation

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#47]
# Problem
Some export functions appear in the [summary](https://geostat-framework.readthedocs.io/projects/gstools/en/stable/tools.html#export) of the documentation, but they are missing in detail:
- to_vtk_structured
- to_vtk_unstructured
- to_vtk

Here they are added to the summary:
https://github.com/GeoStat-Framework/GSTools/blob/5326163d567a6ac0121ca75c007c2ae7d46564b7/gstools/tools/__init__.py#L11

But they are not imported here:
https://github.com/GeoStat-Framework/GSTools/blob/5326163d567a6ac0121ca75c007c2ae7d46564b7/gstools/tools/__init__.py#L41

# Options
- [x] add functions to toplevel in ``tools``
- [ ] remove from summary there

**Comment by LSchueler** [comment]
I vote for adding the functions to toplevel
