### ISSUE TITLE
Typo in variogram doc-string

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#64]
https://github.com/GeoStat-Framework/GSTools/blob/4bde6a0ac6d124234c671ff469c5448440423d57/gstools/variogram/variogram.py#L91

This is a serious typo at this point.

**Comment by LSchueler** [comment]
Are we being a little dramatic lately?! :-D

**Comment by LSchueler** [comment]
Are we being a little dramatic lately?! :-D

**Comment by MuellerSeb** [comment]
:relieved:

**Comment by LSchueler** [comment]
Fixed with commit 32aa702.
