### ISSUE TITLE
Missing prebuilt binary packages for Cython modules

### ISSUE THREAD

**Issue by LSchueler** [GeoStat-Framework/GSTools#7]
As @mralbu pointed out, not everybody can compile the Cython generated C code. We need to prebuild and ship these binary packages.

**Comment by MuellerSeb** [comment]
With https://github.com/GeoStat-Framework/GSTools/commit/f0b9a9ec5ca705e806075701600a15498a348f30 we implemented workflows for Travis-CI and AppVeyor that provide wheels for py27, py35, py36 on linux, macOS, and Windows for 32 and 64 bit each. 
So this issue will be closed.
