### ISSUE TITLE
Typo for in keyword argument for vario_estimate_structured

### ISSUE THREAD

**Issue by TobiasGlaubach** [GeoStat-Framework/GSTools#80]
Hi,
Thanks for the awsome toolbox and the good work.

I found a little mistake in the documentation for "vario_estimate_structured". The docstring says the keyword is: "mathoron", however the default (and accepted) spelling is "matheron". No big issue, just wanted to report it :-)

Thanks again,
Tobi

**Comment by MuellerSeb** [comment]
Thanks for reporting!

**Comment by MuellerSeb** [comment]
Fixed with https://github.com/GeoStat-Framework/GSTools/pull/78/commits/1c0428d782daee224398f406b4a6e417fccea97f
