### ISSUE TITLE
"numpy.ufunc size changed" Error  on Python 3.5

### ISSUE THREAD

**Issue by mmaelicke** [GeoStat-Framework/GSTools#84]
Hey there,

I ran into this import error this morning while importing `gstools==1.2.1` . 

![image](https://user-images.githubusercontent.com/2826034/80790857-422cb880-8b90-11ea-8367-173a3cc06b48.png)

I installed a clean conda environment to reproduce, the `conda env export` output can be found below:

```
name: py35
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2018.8.24=py35_1
  - cycler=0.10.0=py35hcc71164_0
  - freetype=2.9.1=ha9979f8_1
  - geos=3.6.2=h9ef7328_2
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2019.4=245
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.0.1=py35h6538335_0
  - libpng=1.6.37=h2a8f88b_0
  - llvmlite=0.24.0=py35h6538335_0
  - matplotlib=3.0.0=py35hd159220_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35hdbbee80_0
  - mkl_random=1.0.1=py35h77b88f5_1
  - nose=1.3.7=py35_2
  - numba=0.39.0=py35h830ac7b_0
  - numpy=1.15.2=py35ha559c80_0
  - numpy-base=1.15.2=py35h8128ebf_0
  - openssl=1.1.1g=he774522_0
  - pandas=0.23.4=py35h830ac7b_0
  - pip=10.0.1=py35_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py35h6538335_2
  - python=3.5.6=he025d50_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - qt=5.9.7=vc14h73c81de_0
  - scikit-learn=0.20.0=py35heebcf9a_1
  - scipy=1.1.0=py35h4f6bf74_1
  - setuptools=40.2.0=py35_0
  - shapely=1.6.4=py35hc90234e_0
  - sip=4.19.8=py35h6538335_0
  - six=1.11.0=py35_1
  - sqlite=3.31.1=h2a8f88b_1
  - tbb=2020.0=h74a9793_0
  - tbb4py=2018.0.5=py35he980bc4_0
  - tornado=5.1.1=py35hfa6e2cd_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.31.1=py35_0
  - wincertstore=0.2=py35hfebbdb8_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - cython==0.29.17
    - emcee==3.0.2
    - gstools==1.2.1
    - hankel==1.0.2
    - mpmath==1.1.0
    - pyevtk==1.1.1
    - pykrige==1.5.0
```

Tested on my rarely-used Windows machine. Unfortunately, I have no Linux system available at the moment to reproduce, but happened on a Travis `xenial` build ([log here](https://travis-ci.org/github/mmaelicke/scikit-gstat/jobs/681828631)) this morning in the first place.

I can confirm, that this does not happen on Python 3.6 or 3.7.

Do you have any ideas? 
Thanks!

**Comment by mmaelicke** [comment]
Quick update:

I noticed that the I wrote `fields` and not `field` in the import statement, which does not affect the error. 

This does not happen for `gstools==1.1.*`, only for `gstools==1.2.*` as you can see from the screenshot below:

![image](https://user-images.githubusercontent.com/2826034/80792978-14e30900-8b96-11ea-9fac-20309d64b824.png)

Therefore I will just switch to version 1.1 for now.

**Comment by MuellerSeb** [comment]
Hey there!
This is an often reported Error, that comes from numpy. See for example:
- https://github.com/numpy/numpy/issues/12785
- https://github.com/scikit-learn-contrib/hdbscan/issues/272
- ...

you are using `numpy=1.15.2`. An often mentioned workaround is to update numpy to `>1.16`.

Could you try that? Sorry for the inconvenience. 

Only thing we could do is, to update the conda recipe:
https://github.com/conda-forge/gstools-feedstock/blob/525aa3dc5cdb6ad7b72fe71ff4423ec2ff172752/recipe/meta.yaml#L33

It is strange, that the provided `{{ pin_compatible('numpy') }}` gives an incompatible version. We would need to change that line to:
```
numpy>=1.16.0,<2.0
```

Cheers,
Sebastian

**Comment by mmaelicke** [comment]
Thanks for the quick reply. 
Yes, I can confirm that upgrading to numpy 1.16 solved the problem, as well.
Best,
Mirko

**Comment by MuellerSeb** [comment]
Cool. I think we need to update the conda recipe then...

**Comment by MuellerSeb** [comment]
And a side-note:
On conda we only directly support py36-py38 (See [here](https://github.com/conda-forge/gstools-feedstock)) and you mixed conda installs and pip installs, which is mostly a bad idea.
Try updating to a new conda version.
