### ISSUE TITLE
A new tutorial for `Field.mesh()`

### ISSUE THREAD

**Issue by LSchueler** [GeoStat-Framework/GSTools#93]
We should add a tutorial showing how to use the `Field.mesh` method to generate random fields on pre-existing meshes.

**Comment by MuellerSeb** [comment]
You are totally right! I'll take a look at this next week.

**Comment by banesullivan** [comment]
It'd be awesome to have this tutorial use PyVista 😉

**Comment by LSchueler** [comment]
Why not provide 2 or more tutorials? - Maybe you already have something like a minimal working example?
I can also beef it up a little with text, if you just want to provide the mesh file and the code.

**Comment by MuellerSeb** [comment]
There are now some tutorials with `MeshIO`: #112. PyVista examples still missing, but the interface is now ready: #59

**Comment by MuellerSeb** [comment]
ogs5py has its own tutorial: https://geostat-framework.readthedocs.io/projects/ogs5py/en/stable/tutorial_02_pump.html

**Comment by MatusGasparik** [comment]
Even though this issue has been already closed, what I am still missing is a tutorial with the `Field.mesh()` + `pyvista` in conjunction with the `Field.transform()` functionality. I am not quite sure what is the best way to use the two APIs together...

Calling the `Field.mesh()` with an instance of the `pv.Grid` as an arg, saves the field into the `pv.Grid`. What if you then want to generate some transformations of the original field using `Field.transform()` and also want to have these saved in the `pv.Grid` as well? 

Inspired by the example for [discrete fields](https://geostat-framework.readthedocs.io/projects/gstools/en/stable/examples/07_transformations/02_discrete.html#sphx-glr-examples-07-transformations-02-discrete-py), this is how I got it to work: 

```python
import gstools as gs
import pyvista as pv

dim, spacing = (30, 20, 10), (.1, .1, 0.1)
grid = pv.UniformGrid(dim, spacing)

model = gs.Gaussian(dim=3, len_scale=[2, 1, 0.1])
srf = gs.SRF(model, seed=19970221)

srf.mesh(grid, points="points", name="random-field")          # stores "random-field" scalar array in the `grid` object

vals = np.linspace(np.min(srf.field), np.max(srf.field), 5)
srf.transform("discrete", field="field", store="discrete", values=vals)     # stores "discrete" field in `srf` object

grid['discrete'] = srf['discrete']          # copies data from `srf` to `grid`


plotter = pv.Plotter(window_size=(800, 600))
plotter.background_color = 'gray'
plotter.enable_anti_aliasing()
plotter.add_mesh(grid, scalars="discrete", show_edges=True)
plotter.show()
``` 
Result:

![image](https://user-images.githubusercontent.com/15058994/144221566-4b439fa8-111b-4642-bf40-b028eb50b8da.png)

Is this how those two APIs are  supposed to be used together? It would make sense to call `srf.mesh` after all the transformed fields have been defined in, or can subsequent calls of `srf.mesh` be used to add new fields to the `pv.Grid` object?

**Comment by banesullivan** [comment]
Just a drive-by thought/comment:

After calling, `srf.mesh`, `srf` could keep a pointer to the mesh and add fields to it anytime an operation is performed. Otherwise, `grid['discrete'] = srf['discrete']` is exactly what you'd have to do.

------

I also want to give a plug for an example I put together here: https://banesullivan.com/pyvista/examples/kriging.html

**Comment by MuellerSeb** [comment]
As @banesullivan pointed out, you can add more fields afterwards. Closing this for now. If you have further ideas on how to improve the interoperability, just open another issue or discussion.
