### ISSUE TITLE
Get semivariance value at defined lag from model

### ISSUE THREAD

**Issue by jacobgrasmick** [GeoStat-Framework/GSTools#96]
Hi,

I am just getting started with gstools - very useful! My question is, if I have a model variogram (covmodel), how can I extract the semivariance value at any specified lag? What I am aiming to do is compute the error between the model and experimental variogram at each binned lag.

Thanks!

**Comment by MuellerSeb** [comment]
Hey there,

what we are doing (in the fitting routines for example) is, we evaluate the `model.variogram(x)` at the bin-centers.

Does that help?

**Comment by jacobgrasmick** [comment]
Thanks MuellerSeb. That's precisely what I was looking for.
